### ISSUE TITLE
Building Tinker-OpenMM from source

### ISSUE THREAD

**Issue by Maxim-93** [TinkerTools/tinker-openmm#3]
Hi there!

I’m trying to build Tinker-OpenMM from source and i’m encountering the following error message on stage 6 after running $make all, as specified in the invocation options contained in ’Makefile’.

g++ -c -Ofast -msse3 -fopenmp -I/usr/local/openmm/include ommstuf.cpp
ommstuf.cpp:57:10: fatal error: OpenMMCWrapper.h: No such file or directory
 #include "OpenMMCWrapper.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [ommstuf.o] Error 1

As for a bit of extra context, I’m in an anaconda environment containing OpenMM 7.5 which I installed using:

$conda install -c conda-forge openmm=7.5.0

How should I proceed?

Many thanks,
Max

**Comment by jayponder** [comment]
Hi, Unfortunately, it is not possible to build Tinker-OpenMM at this time. Please see the "README" on the main GitHub page for the Tinker-OpenMM repository. We do still plan to get this working again at some point in the future. But due to the rather major changes made by the OpenMM developers in spring 2021, it will require a fairly large amount of work to get Tinker-OpenMM running again.

In the meantime, I might suggest that you try building the "Tinker9" GPU code, which is available from the same TinkerTools organization page on GitHub. Tinker9 is actually significantly faster than OpenMM for the AMOEBA polarizable multipole force field (in case that is why you wanted Tinker-OpenMM..). Tinker9 is somewhat slower than OpenMM for the typical fixed partial charge Amber, CHARMM and OPLS-AA force fields, but its performance is reasonable for these simple models as well.

**Comment by Maxim-93** [comment]
Hi Jay,

Thank you so much for your quick response! Is it possible to perform AMOEBA ABFE calculations with Tinker9? If so, then I'll definitely give it a go.

Max

**Comment by jayponder** [comment]
Yes, my group has done and is doing lots of ABFE calculations, and we use Tinker9 for all the MD calculations and for the BAR analysis to extract the actual free energy values.
