### ISSUE TITLE
Error in ommstuf.cpp while building tinker-openmm interface.

### ISSUE THREAD

**Issue by RimpiDey** [TinkerTools/tinker-openmm#4]
![SD_Tinker_issue](https://github.com/TinkerTools/tinker-openmm/assets/125631865/85b393b7-3468-473f-b312-58a86e7d53e0)
I was trying to build tinker-openmm interface but I am getting the following error (please refer to the image uploaded)

ERROR:
After typing the command "make all", is shows the error,
ommstuf.cpp(2991): error: identifier "OpenMM_AmoebaVdwForce_addParticle_1" is undefined
           OpenMM_AmoebaVdwForce_addParticle_1 (amoebaVdwForce, vdw__.ired[ii]-1, cdnstype, vdw__.kred[ii], isAlchemical);
Can someone please help me in resolving this problem?

**Comment by jayponder** [comment]
As is mentioned in bold on the main GitHub page for Tinker-OpenMM, this package is not up to date, and does not build correctly against the current OpenMM since March 2021. We have left it on GitHub mostly as a code sample, and in the hope that we or someone else might try to get it working with current OpenMM.

If you want to use "Tinker" on GPUs, please try the Tinker9 package, which is also available on the main TinkerTools organization GitHub site.
